### ISSUE TITLE
[BUG]CodeSeeder cache broke deploy

### ISSUE THREAD

**Issue by jinxiao** [awslabs/aws-codeseeder#195]
**Describe the bug**

When We tried to deploy seedfarmer modules from local, we always must delete the SeedFarmer cache otherwise it tries to deploy the wrong code: 

```
rm -rf codeseeder.out
```
 
If this not be done, seedfarmer will use the old code to deploy.
**To Reproduce**
1. Use one revision to deploy
2. Update to another revision.
3. re-deploy.
4. Without deleting codeseeder.out, it will use the previous revision.

**Expected behavior**
We expect to use the newest revision each time.

**Comment by dgraeber** [comment]
@jinxiao I just ran some tests to replicate (via SeedFarmer and AWS-CodeSeeder) using seed-farmer==4.0.1 and aws-codeseder==1.0.0

How I tried to replicate:
1. Use the [dummy module in IDF](https://github.com/awslabs/idf-modules/tree/main/modules/dummy/blank)  as it does evrerything but actually deploy code
2. configured my manifests to run locally:
```
name: dummy
path: modules/dummy/blank
targetAccount: primary
targetRegion: us-east-1
```
3. Deployed and investigated `codeseeder.out/dummy-pre-dummy-dummy/bundle/module` and confirmed all files were there and correct
4. Added `modules/dummy/blank/app.py` to the local code and redeployed (interrogate the codeseeder.out again to confirm all files)
5. Modified `modules/dummy/blank/app.py` on the local code and redeployed (interrogate the codeseeder.out again to confirm all files)
6. Deleted `modules/dummy/blank/app.py` on the local code and redeployed (interrogate the codeseeder.out again to confirm all files)
7. Destroy the deployment

**In each step, the files looked correct (app.py was added to codeseeder.out/dummy-pre-dummy-dummy/bundle.zip, updated on bundle and local, and properly deployed).**  

I then looked at the aws-codeseeder code and confirmed that we delete the bundle directory on every deployment (ref: aws-codeseeder/aws_codeseeder/_bundle.py line 90 `shutil.rmtree(final_dir)`) and I can see that the bundle.zip is getting update with the new files.

I cannot replicate your issue currently, so I would like more information so I can try and replicate.

Please provide more information?  Please provide your seed-farmer and  aws-codeseeder versions, reference to manifests and the steps you took to replicate so I can try and reproduce locally?

**Comment by jinxiao** [comment]
Hi, team

Another information I want to provide.
We're using seedfarmer 3.5.2.

I highly suspect that it is relegated that we abuse git tags as branches and completely use git wrongly with this migration script created by AWS.

I.e. if we would use a branch for cn-baseline and do not change where tags point to all the time, see:

 
![image](https://github.com/awslabs/aws-codeseeder/assets/2718196/44864ef2-74ae-4075-b9f2-17ca9da89c55)

So my concern is that, if the git tag cannot work properly, when I use the code with git tag, it will failed or not?

some code snippets we used:

```yaml
name: ecr-file-quality-checks
path: git::codecommit://CrossAccountAccessProfile@orion-modules.git//modules/optionals/ecr/?ref=om-ecr-v1.0.2
parameters:
  - name: REPOSITORY_NAME
    valueFrom:
      envVariable: FILE_QUALITY_CHECKS_REPO_NAME
```

**Comment by dgraeber** [comment]
I am not sure I understand the question, but I an provide this information:  CodeSeeeder properly updates the code in the bundle on each deployment invocation (this has been vetted and proven).

Seed-Farmer is the API that pulls from Git (or CodeCommit).  It follows the standards of normal git processing.  It can reference branches, tags and commit hashes.  In order to properly work, the cloned repo must not be in a detached state (i.e. all tags and branches must not be in a detached state when cloned).  Anything related to tag management is outside the responsibility of SeedFarmer and CodeSeeder.
