### ISSUE TITLE
[FEATURE] Expose CFN stack commands for ProjectManagedPolicy

### ISSUE THREAD

**Issue by dgraeber** [awslabs/aws-codeseeder#22]
Lets discuss feasibility of below...?

**Is your feature request related to a problem? Please describe.**
Similar to the creation of the seedkit toolkit, our code calls the creation of a project managed policy that is digging deep into the codeseeder codebase.  

**Describe the solution you'd like**
Create a command level function that will check if the managed policy stack is deployed, return a boolean, the stackname and output.  
Create a command level function that will create the stack
Create a command level function to destroy the stack

A similar solution to this issue, but for the managed policy:
https://github.com/awslabs/aws-codeseeder/issues/20
https://github.com/awslabs/aws-codeseeder/pull/21

**Comment by chamcca** [comment]
implemented
