### ISSUE TITLE
[FEATURE] asynchronous `remote_function` support

### ISSUE THREAD

**Issue by chamcca** [awslabs/aws-codeseeder#33]
**Is your feature request related to a problem? Please describe.**
At times it may be necessary to asynchronously execute the `remote_function` code. Currently the processes blocks until the CodeBuild execution completes or errors.

**Describe the solution you'd like**
A mechanism for flagging a `remote_function` for asynchronous execution. When the function executes, rather than blocking until CodeBuild completes or errors, the library could block until CodeBuild starts, then return the ExecutionId. A secondary function to rejoin and/or check execution status and retrieve any return values will also be required. 

**Additional context**
The use case being targeted is to begin execution of a `remote_function` within AWS Lambda function and then check execution status with another Lambda function. This would enable CodeSeeder workflows to be used in AWS StepFunctions StateMachines. For this to work, the asynchronous `remote_function` will need to return the CodeBuild ExecutionID so that it can be returned from the Lambda. subsequent Lambda functions would take the ExecutionID as input and use it to check Execution status.

**Comment by dgraeber** [comment]
There is no demand for this...closing
