### ISSUE TITLE
Does not support deployments triggered from windows environment

### ISSUE THREAD

**Issue by otyrrell** [awslabs/aws-codeseeder#80]
Due the the direct string replacements used to transform the absolute local path of the source files to a bundle relative path we bundle the entire local path when running in a windows environment. Suggest fixing as follows within _bundle.py:

`zip_relative_path = os.path.relpath(pathlib.Path(path), pathlib.Path(root_dir))
                zf.write(path, zip_relative_path)`

**Comment by dgraeber** [comment]
Thanks @otyrrell  - we will look into ths.

**Comment by otyrrell** [comment]
#81
